### ISSUE TITLE
not working for GameStages-1.12.2-2.0.123

### ISSUE THREAD

**Issue by Woody-0w0** [Darkhax-Minecraft/WailaStages#5]
Is this mod works only for SevTech: Ages?

**Comment by Woody-0w0** [comment]
crash log：
Description: Unexpected error

java.lang.NoClassDefFoundError: net/darkhax/gamestages/capabilities/PlayerDataHandler
    at com.jarhax.wailastages.WailaStages.getTooltipText(WailaStages.java:64)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_846_WailaStages_getTooltipText_WailaTooltipEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:62)
    at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:54)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:93)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.darkhax.gamestages.capabilities.PlayerDataHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 21 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 23 more

**Comment by Woody-0w0** [comment]
i'm not a programmer.
comparing ecompiled-code with JourneyMapStages released on Mar 4, 2019:
```       
 final EntityPlayer player = (EntityPlayer)Minecraft.func_71410_x().field_71439_g;
 final PlayerDataHandler.IStageData stages = PlayerDataHandler.getStageData(player);
```
the code of WailaStages released on May 2, 2018 :
```
final PlayerDataHandler.IStageData stageData = PlayerDataHandler.getStageData(PlayerUtils.getClientPlayer());
```
i think a update is needed

**Comment by Darkhax** [comment]
I just set up a test pack and can confirm this mod works as expected using the latest recommended release of each dependency. 

- Bookshelf 2.3.590
- CraftTweaker 4.1.20.680
- Game Stages 2.0.123
- Hwyla 1.8.26-B41
- Waila Stages 2.0.24

This mod is not limited to SevTech ages and can be used in other packs as long as you follow the license.
